services:
 - type: web
   name: webprodavnica-backend
   runtime: node
   rootDir: backend
   plan: free
   buildCommand: npm install
   startCommand: npm start
 - type: web
   name: webprodavnica-frontend
   runtime: static
   rootDir: frontend
   buildCommand: npm install && npm run build
   staticPublishPath: dist