services:
 - type: web
   name: webprodavnica-backend
   env: node
   rootDir: backend
   plan: free
   buildCommand: npm ci && chmod +x start.sh
   startCommand: ./start.sh
 - type: web
   name: webprodavnica-frontend
   env: static
   rootDir: frontend
   plan: starter
   buildCommand: npm ci && npm run build
   startCommand: npx serve -s dist